baseURL = "https://juliesparks.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Julie Sparks Personal Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Security Musings"
author = "Julie Sparks"
description = "Security Engineer at Cloudflare. Philomath. Alumna of Rollins College."
profilePicture = "images/juliecloudflare.png"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/julie-a-sparks/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/julieagnessparks"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:julieagnessparks@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "post"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Resume"
  weight = 400
  identifier = "resume"
  url = "/resume/"
